---
abstract: 'The CPAN Testers Reports website'
author:
  - 'Barbie (BARBIE) <barbie@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 7.1104, CPAN::Meta::Converter version 2.150005'
keywords:
  - qa
  - cpan
  - testing
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: CPAN-Testers-WWW-Reports
no_index:
  directory:
    - t
    - inc
    - t
    - examples
    - vhost
requires:
  CGI: '0'
  CPAN::Testers::Common::Article: '0'
  CPAN::Testers::Common::Utils: '0'
  CPAN::Testers::Fact::LegacyReport: '0'
  CPAN::Testers::Fact::TestSummary: '0'
  Carp: '0'
  Class::Accessor::Fast: '0'
  Clone: '0'
  Cwd: '0'
  Data::Dumper: '0'
  Data::FlexSerializer: '0'
  Email::Address: '0'
  File::Basename: '0'
  File::Find::Rule: '0'
  File::Path: '0'
  File::Slurper: '0'
  GD::Graph::colour: '0'
  GD::Graph::lines: '0'
  Getopt::Long: '0'
  HTML::Entities: '0'
  IO::File: '0'
  JSON::MaybeXS: '0'
  Labyrinth: '5.27'
  Labyrinth::DIUtils::ImageMagick: '5.04'
  Labyrinth::Plugin::CPAN: '3.50'
  Labyrinth::Plugin::Core: '5.18'
  Labyrinth::Plugin::Requests: '1.00'
  Metabase::Resource: '0'
  Sort::Versions: '0'
  Time::Local: '0'
  WWW::Mechanize: '0'
  XML::RSS: '0'
  YAML::XS: '0'
  version: '0'
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=CPAN-Testers-WWW-Reports
  homepage: https://www.cpantesters.org
  repository: https://github.com/barbie/cpan-testers-www-reports.git
version: '3.56'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
